name: rendertest

on:
  workflow_dispatch:

jobs:
  run-newsminder:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x              
        
      - name: Run Capture
        run: nexrender-cli-macos --file MyJob.json
        
      # Add new files in data folder, commit along with other modified files, push
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
